sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t 696515/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true 696515/react-test npm test

after_success:
  - docker build -t 696515/multi-client ./client
  - docker build -t 696515/multi-nginx ./nginx
  - docker build -t 696515/multi-server ./server
  - docker build -t 696515/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push 696515/multi-client
  - docker push 696515/multi-nginx
  - docker push 696515/multi-server
  - docker push 696515/multi-worker


deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker1'
  env: 'Multidocker1-env'
  bucket_name: 'elasticbeanstalk-us-east-2-982751471336'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY